name: "Linting Tests"
on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "K6/**"
      - "conf"
run-name: "linting"
permissions:
  contents: "read"
jobs:
  checks:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98"
      - name: "Use Node.js"
        uses: "actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238"
        with:
          node-version: "24.x"
      - name: "Dependencies"
        run: "npm install"
      - name: "Lint Code"
        run: "npm run lint"
      - name: "Ensure javascript files are Kebab Case"
        run: "./validate.sh"
        shell: "bash"
  validate_generation:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98"
      - uses: "Altinn/altinn-platform/actions/generate-k6-manifests@bfff0d4e624bcc96321727367c865e5ed6dcffc8"
        with:
          config_file: "${{ matrix.config_file }}"
      - name: "Tree"
        run: "tree .dist/"
        shell: "bash"
    strategy:
      matrix:
        config_file:
          - "K6/api/tests/portaler/breakpoint.yaml"
          - "K6/api/tests/portaler/healthcheck.yaml"
          - "K6/api/tests/dialogporten/serviceowner/functional.yaml"
          - "K6/api/tests/dialogporten/serviceowner/breakpoint.yaml"
          - "K6/api/tests/authentication/register/functional.yaml"
          - "K6/api/tests/authentication/connections/functional.yaml"
          - "K6/api/tests/authentication/connections/smoke.yaml"
          - "K6/api/tests/authentication/connections/breakpoint.yaml"
          - "K6/api/tests/authentication/resource-registry/healthcheck.yaml"
          - "K6/api/tests/authentication/pdp-authorize/functional.yaml"
          - "K6/api/tests/authentication/pdp-authorize/smoke.yaml"
          - "K6/api/tests/authentication/pdp-authorize/breakpoint.yaml"
          - "K6/api/tests/authentication/system-register/functional.yaml"
          - "K6/api/tests/authentication/get-authorized-parties/functional.yaml"
          - "K6/api/tests/authentication/get-authorized-parties/smoke.yaml"
          - "K6/api/tests/authentication/get-authorized-parties/for-user-many-parties/smoke.yaml"
          - "K6/api/tests/authentication/get-authorized-parties/breakpoint.yaml"
          - "K6/api/tests/authentication/roles/functional.yaml"
          - "K6/api/tests/authentication/roles/smoke.yaml"
          - "K6/api/tests/authentication/roles/breakpoint.yaml"
          - "K6/api/tests/authentication/system-user-request/functional.yaml"
          - "K6/api/tests/authentication/consent/functional.yaml"
          - "K6/api/tests/authentication/consent/smoke.yaml"
          - "K6/api/tests/authentication/consent/breakpoint.yaml"
          - "K6/api/tests/platform/service_owner/healthcheck.yaml"
          - "K6/api/tests/core/notifications/functional.yaml"
          - "K6/api/tests/core/notifications/order-with-reminders/functional.yaml"
