name: Auth - run k6 smoke tests

on:
  workflow_dispatch:
    inputs:
      configFilePath:
        description: "Configuration file for the test runs"
        required: true
        default: "conf/auth-smoke.yaml"

      testName:
        type: choice
        description: "The test to run"
        options:
          - pdp-authorize-enduser
          - pdp-authorize-dagl
          - pdp-authorize-dagl-dd
          - pdp-authorize-dagl-deny
          - get-roles
          - get-authorized-parties-org
          - get-authorized-parties-user
          - get-auth-parties-user-al
          - get-auth-parties-user-dp
          - get-auth-parties-user-dp-wf
          - get-authorized-parties-sysuser
          - get-connections-to
          - get-connections-from
          - get-access-packages-to
          - get-access-packages-from

      vus:
        description: "The number of VUs to run the test with"
        required: false
        type: number
        default: 1

      duration:
        description: "Duration of the test"
        required: false
        default: 1m

      commandLineArgs:
        description: "Command line arguments to pass to the k6 run command"
        required: false
        default: ""

  schedule:
    - cron: "0 * * * *"
    - cron: "4 * * * *"
    - cron: "8 * * * *"
    - cron: "12 * * * *"
    - cron: "16 * * * *"
    - cron: "20 * * * *"
    - cron: "24 * * * *"
    - cron: "28 * * * *"
    - cron: "32 * * * *"
    - cron: "36 * * * *"
    - cron: "40 * * * *"
    - cron: "44 * * * *"
    - cron: "48 * * * *"
    - cron: "52 * * * *"
    - cron: "56 * * * *"

run-name: Auth - run smoke test for ${{ inputs.testName }} - ${{ inputs.vus }} VUs for ${{ inputs.duration }}
permissions:
  id-token: write
  contents: read

jobs:
  k6-smoketest:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup k8s client
        uses: ./.github/actions/setup-k8s
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Process CLI args
        shell: bash
        run: |
          VUS="${VUS:-}"
          DURATION="${DURATION:-}"
          COMMAND_LINE_ARGS="${COMMAND_LINE_ARGS:-}"

          OUTPUT=""

          if [ -n "$VUS" ]; then
            OUTPUT="$OUTPUT --vus=$VUS"
          fi

          if [ -n "$DURATION" ]; then
            OUTPUT="$OUTPUT --duration=$DURATION"
          fi

          if [ -n "$COMMAND_LINE_ARGS" ]; then
            OUTPUT="$OUTPUT $COMMAND_LINE_ARGS"
          fi

          # Remove leading whitespace
          OUTPUT=$(echo "$OUTPUT" | sed 's/^[[:space:]]*//')

          # Output the final string
          echo "COMMAND_LINE_ARGS=$OUTPUT" >> $GITHUB_ENV
        env:
          VUS: ${{ inputs.vus }}
          DURATION: ${{ inputs.duration }}
          COMMAND_LINE_ARGS: ${{ inputs.commandLineArgs }}

      - name: Generate k8s manifests
        uses: Altinn/altinn-platform/actions/generate-k6-manifests@main
        with:
          config_file: "${{ inputs.configFilePath || 'conf/auth-smoke.yaml' }}" # No inputs when running as a cron
          command_line_args: ${{ env.COMMAND_LINE_ARGS }}

      - name: Run smoke test for .dist/yt01-pdp-authorize-enduser
        if: github.event.schedule == '0 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-pdp-authorize-enduser

      - name: Run smoke test for .dist/yt01-pdp-authorize-dagl
        if: github.event.schedule == '4 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-pdp-authorize-dagl

      - name: Run smoke test for .dist/yt01-pdp-authorize-dagl-dd
        if: github.event.schedule == '8 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-pdp-authorize-dagl-dd

      - name: Run smoke test for .dist/yt01-pdp-authorize-dagl-deny
        if: github.event.schedule == '12 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-pdp-authorize-dagl-deny

      - name: Run smoke test for .dist/yt01-get-roles
        if: github.event.schedule == '16 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-roles

      - name: Run smoke test for .dist/yt01-get-authorized-parties-org
        if: github.event.schedule == '20 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-authorized-parties-org

      - name: Run smoke test for .dist/yt01-get-authorized-parties-sysuser
        if: github.event.schedule == '24 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-authorized-parties-sysuser

      - name: Run smoke test for .dist/yt01-get-authorized-parties-user
        if: github.event.schedule == '28 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-authorized-parties-user

      - name: Run smoke test for .dist/yt01-get-connections-to
        if: github.event.schedule == '32 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-connections-to

      - name: Run smoke test for .dist/yt01-get-connections-from
        if: github.event.schedule == '36 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-connections-from

      - name: Run smoke test for .dist/yt01-get-access-packages-to
        if: github.event.schedule == '40 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-access-packages-to

      - name: Run smoke test for .dist/yt01-get-access-packages-from
        if: github.event.schedule == '44 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-access-packages-from

      - name: Run smoke test for .dist/yt01-get-auth-parties-user-al
        if: github.event.schedule == '48 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-auth-parties-user-al

      - name: Run smoke test for .dist/yt01-get-auth-parties-user-dp
        if: github.event.schedule == '52 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-auth-parties-user-dp

      - name: Run smoke test for .dist/yt01-get-auth-parties-user-dp-wf
        if: github.event.schedule == '56 * * * *'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-get-auth-parties-user-dp-wf

      - name: Apply k8s manifests
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-${{ inputs.testName }}
