name: "authentication - run k6 smoke tests"
on:
  schedule:
    - cron: "20 * * * *"
run-name: "run smoke"
permissions:
  contents: "read"
  id-token: "write"
jobs:
  k6-smoke:
    environment: "test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8"
      - name: "Setup k8s client"
        uses: "./.github/actions/setup-k8s"
        with:
          azure-client-id: "${{ secrets.AZURE_CLIENT_ID }}"
          azure-subscription-id: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          azure-tenant-id: "${{ secrets.AZURE_TENANT_ID }}"
      - name: "Generate k8s manifests"
        uses: "Altinn/altinn-platform/actions/generate-k6-manifests@bfff0d4e624bcc96321727367c865e5ed6dcffc8"
        with:
          config_file: "K6/api/tests/authentication/connections/smoke.yaml"
      - name: "Apply k8s manifests"
        run: "kubectl apply --server-side -f .dist/ -R || true"
        shell: "bash"
      - name: "Generate k8s manifests"
        uses: "Altinn/altinn-platform/actions/generate-k6-manifests@bfff0d4e624bcc96321727367c865e5ed6dcffc8"
        with:
          config_file: "K6/api/tests/authentication/pdp-authorize/smoke.yaml"
      - name: "Apply k8s manifests"
        run: "kubectl apply --server-side -f .dist/ -R || true"
        shell: "bash"
      - name: "Generate k8s manifests"
        uses: "Altinn/altinn-platform/actions/generate-k6-manifests@bfff0d4e624bcc96321727367c865e5ed6dcffc8"
        with:
          config_file: "K6/api/tests/authentication/get-authorized-parties/smoke.yaml"
      - name: "Apply k8s manifests"
        run: "kubectl apply --server-side -f .dist/ -R || true"
        shell: "bash"
      - name: "Generate k8s manifests"
        uses: "Altinn/altinn-platform/actions/generate-k6-manifests@bfff0d4e624bcc96321727367c865e5ed6dcffc8"
        with:
          config_file: "K6/api/tests/authentication/get-authorized-parties/for-user-many-parties/smoke.yaml"
      - name: "Apply k8s manifests"
        run: "kubectl apply --server-side -f .dist/ -R || true"
        shell: "bash"
      - name: "Generate k8s manifests"
        uses: "Altinn/altinn-platform/actions/generate-k6-manifests@bfff0d4e624bcc96321727367c865e5ed6dcffc8"
        with:
          config_file: "K6/api/tests/authentication/roles/smoke.yaml"
      - name: "Apply k8s manifests"
        run: "kubectl apply --server-side -f .dist/ -R || true"
        shell: "bash"
      - name: "Generate k8s manifests"
        uses: "Altinn/altinn-platform/actions/generate-k6-manifests@bfff0d4e624bcc96321727367c865e5ed6dcffc8"
        with:
          config_file: "K6/api/tests/authentication/consent/smoke.yaml"
      - name: "Apply k8s manifests"
        run: "kubectl apply --server-side -f .dist/ -R || true"
        shell: "bash"
