name: Auth - run k6 smoke tests

on:
  workflow_dispatch:
    inputs:
      configFilePath:
        description: "Configuration file for the test runs"
        required: true
        default: "conf/auth-smoke.yaml"

      testName:
        type: choice
        description: "The test to run"
        options:
          - pdp-authorize-enduser
          - pdp-authorize-dagl
          - pdp-authorize-dagl-dd
          - pdp-authorize-dagl-deny
          - get-roles
          - get-authorized-parties-org
          - get-authorized-parties-user
          - get-auth-parties-user-al
          - get-auth-parties-user-dp
          - get-auth-parties-user-dp-wf
          - get-authorized-parties-sysuser
          - get-connections-to
          - get-connections-from
          - get-access-packages-to
          - get-access-packages-from

      vus:
        description: "The number of VUs to run the test with"
        required: false
        type: number
        default: 1

      duration:
        description: "Duration of the test"
        required: false
        default: 1m

      commandLineArgs:
        description: "Command line arguments to pass to the k6 run command"
        required: false
        default: ""

  schedule:
    - cron: "27 * * * *"

permissions:
  id-token: write
  contents: read

jobs:
  k6-smoketest:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup k8s client
        uses: ./.github/actions/setup-k8s
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Process CLI args
        shell: bash
        run: |
          VUS="${VUS:-}"
          DURATION="${DURATION:-}"
          COMMAND_LINE_ARGS="${COMMAND_LINE_ARGS:-}"

          OUTPUT=""

          if [ -n "$VUS" ]; then
            OUTPUT="$OUTPUT --vus=$VUS"
          fi

          if [ -n "$DURATION" ]; then
            OUTPUT="$OUTPUT --duration=$DURATION"
          fi

          if [ -n "$COMMAND_LINE_ARGS" ]; then
            OUTPUT="$OUTPUT $COMMAND_LINE_ARGS"
          fi

          # Remove leading whitespace
          OUTPUT=$(echo "$OUTPUT" | sed 's/^[[:space:]]*//')

          # Output the final string
          echo "COMMAND_LINE_ARGS=$OUTPUT" >> $GITHUB_ENV
        env:
          VUS: ${{ inputs.vus }}
          DURATION: ${{ inputs.duration }}
          COMMAND_LINE_ARGS: ${{ inputs.commandLineArgs }}

      - name: Generate k8s manifests
        uses: Altinn/altinn-platform/actions/generate-k6-manifests@main
        with:
          config_file: "${{ inputs.configFilePath || 'conf/auth-smoke.yaml' }}" # No inputs when running as a cron
          command_line_args: ${{ env.COMMAND_LINE_ARGS }}

      - name: Apply k8s manifests
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/ -R

      - name: Apply k8s manifests
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          kubectl apply --server-side -f .dist/yt01-${{ inputs.testName }}
